In [1]:
# imports

import numpy as np 
from pprint import pprint as pp

In [3]:
# localizar un elmento en especifico

m = np.arange(24).reshape(4,6)
print(m[3,4])

22


In [8]:
# ordenar matrices de manera ascendente
m1 = np.array([90,7,9,4,2,1])
print(np.sort(m1))

[ 1  2  4  7  9 90]


In [10]:
# elevar a la N potencia todos los elementos de un array

m1 = np.array([4,5,6])
print(np.power(m1, 3))

# tambien se puede hacer de otra forma 
print(m1**2)

[ 64 125 216]
[16 25 36]


In [11]:
# conformar un array booleano apartir de una consulta

m1 = np.array([1,2,3,4,5,6,7,8,9])
print(np.array(m1 >= 4))

[False False False  True  True  True  True  True  True]


In [12]:
# encontrar el mim y max de un array

m1 = np.arange(20)
print(m1.max(), m1.min())

19 0


In [15]:
# combinar o concatenar dos matrices

m1 = np.arange(10)
m2 = np.array([11,12,13,14,15,16,17,18,19])

m3 = np.concatenate((m1,m2))
print(m3)


[ 0  1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [26]:
# suma de matrices 

m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])

print(m1 + m2)

# tambien aplica para la multiplicasion, division y resta

[[ 6  8]
 [10 12]]


In [27]:
# sumar un elemento en todos los de una matriz
m1 = np.array([[1,2], [3,4]])
print(m1 + 2)
# tambien aplica para la multiplicasion, division y resta

[[3 4]
 [5 6]]


In [28]:
# tambien se puede hacer todo lo anterior usando metodos

m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])

print(np.add(m1,m2)) # suma 
print(np.subtract(m1,m2)) # resta 
print(np.multiply(m1,m2)) # multiplica 
print(np.divide(m1,m2)) # divide

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [29]:
# no se que hace esto pero lo agrego

m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])

print(m1.dot(m2))

[[19 22]
 [43 50]]
