In [ ]:
# imports
import numpy as np

funciones estadisticas

Las funciones presentadas, si el array es mayor que 1D se podra hacer el uso de los axis 0 y 1
en caso de que no lo sea asi, y nuestro array es de 1D solo podemos hacer uso de nuestro axis 0.

In [ ]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(m)
print("")

# func para encontrar el valor maximo de un array, independientemente de donde se encuentre
print(np.amax(m))

# func para encontrar el valor minimo de un array, independientemente de donde se encuentre
print(np.amin(m))

In [ ]:
# func para encontrar el valor maximo de cada columna 
print(np.amax(m, axis=1))

# func para encontrar el valor minimo de cada columna
print(np.amin(m, axis=1))

In [ ]:
# func para encontrar el valor maximo de cada fila 
print(np.amax(m, axis=1))

# func para encontrar el valor minimo de cada fila
print(np.amin(m, axis=1))

In [ ]:
# resta el min con el max del array
print(np.ptp(m))

# resta el min con el max de las columnas
print(np.ptp(m, axis=0))

# resta el min con el max de las filas
print(np.ptp(m, axis=1))

In [ ]:
# esta funcion funciona cuando la cantidad de elementos es impar

# retorna el percentil de un array
print(np.percentile(m, 50))

# retorna el percentil de las columnas
print(np.percentile(m, 50, axis=0))

# retorna el percentil de las filas
print(np.percentile(m, 50, axis=1))

In [ ]:
# retorna la media de un array
print(np.median(m))

# retorna la media de las columnas
print(np.median(m, axis=0))

# retorna la media de las filas
print(np.median(m, axis=1))

In [ ]:
# retorna la media aritmetica de un array
print(np.mean(m))

# retorna la media aritmetica de las columnas
print(np.mean(m, axis=0))

# retorna la media aritmetica de las filas
print(np.mean(m, axis=1))

In [30]:
# retorna el promedio ponderado de un array
print(np.average(m))

# retorna el promedio ponderado de las columnas
print(np.average(m, axis=0))

# retorna el promedio ponderado de las filas
print(np.average(m, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [32]:
# retorn la desviacion estandar
print(np.std(m))

# retorna la desviacion estandar de las columnas
print(np.std(m, axis=0))

# retorna la desviacion estandar de las filas
print(np.std(m, axis=1))

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]
